### ISSUE TITLE
小需求

### ISSUE THREAD

**Issue by able9527** [lz520520/railgun#102]
师傅好，试用了一下新版很棒，端口扫描能否增加一个导出execl功能，导出结果将协议ip端口添加在一行，例如：https://xx.xx.xx.xx:8899，这样方便做资产收集分类

**Comment by lz520520** [comment]
这种是否可以
![image](https://github.com/user-attachments/assets/889b941b-f09f-44a0-ac36-d491d1b65b7a)

**Comment by able9527** [comment]
这种也可以，全选->信息提取->http

**Comment by lz520520** [comment]
功能更新了，我关闭issue
