### ISSUE TITLE
rsa md5无法加解密

### ISSUE THREAD

**Issue by laiquziru** [lz520520/railgun#105]
![image](https://github.com/user-attachments/assets/1a928b12-ab15-4848-8036-5f132479595a)

![image](https://github.com/user-attachments/assets/6b0c96b6-6046-4d57-9dc5-52e1b8b164cb)

![image](https://github.com/user-attachments/assets/bb957e8e-8032-48de-9ab1-dcd5c310a7d8)

**Comment by lz520520** [comment]
额，你到底是要加密还是解密，你解密都没选

**Comment by lz520520** [comment]
![image](https://github.com/user-attachments/assets/6e6019f2-f90f-4126-a0f5-069a72c37803)
