### ISSUE TITLE
密码貌似不正确

### ISSUE THREAD

**Issue by JXJZJWHCM** [lz520520/railgun#106]
三个空格这个密码是错误的
![屏幕截图 2024-11-12 142746](https://github.com/user-attachments/assets/d877149c-10d0-415b-a10b-5a79c2b5458d)
![屏幕截图 2024-11-12 142830](https://github.com/user-attachments/assets/4a3c4eb2-1970-4743-b47f-7d90359b2492)

**Comment by coollce** [comment]
railgun

**Comment by JXJZJWHCM** [comment]
自动回复邮件。automatically reply e-mail你好，你的邮件我已收到，将会尽快给你回复。Hello, I have received your email and will reply to you as soon as possible.

**Comment by JXJZJWHCM** [comment]
自动回复邮件。automatically reply e-mail你好，你的邮件我已收到，将会尽快给你回复。Hello, I have received your email and will reply to you as soon as possible.
