### ISSUE TITLE
可以开源吗

### ISSUE THREAD

**Issue by clasy0947** [lz520520/railgun#11]
请问作者愿意开源吗？可以共同开发。

**Comment by lz520520** [comment]
不开源的，这个工具起初也只是方便自己的一些操作，自己需要啥功能就加了啥功能，没有做成一个项目的打算

**Comment by clasy0947** [comment]
明白。我觉得您的工具挺好用的，想添加点自己想要的功能。我想要一份源码，请问可以吗？
