### ISSUE TITLE
Mac新版本编码转换

### ISSUE THREAD

**Issue by ll160803** [lz520520/railgun#111]
![Uploading 15841733300483_.pic_hd.jpg…]()

**Comment by ll160803** [comment]
![Uploading 15841733300483_.pic_hd.jpg…]()

**Comment by ll160803** [comment]
![15841733300483_ pic_hd](https://github.com/user-attachments/assets/f9011a70-4ee6-4958-9586-029c75bd98e7)

**Comment by lz520520** [comment]
这个问题修复了，新版本后续更新

**Comment by lz520520** [comment]
修复了，可以使用新版本
