### ISSUE TITLE
大佬请问启动密码怎么获取？没有您的联系方式，没法儿私聊

### ISSUE THREAD

**Issue by 18cs06** [lz520520/railgun#12]

**Comment by 18cs06** [comment]
你好，启动密码已经知道了，谢谢
1.3.8的在解压时有个解压密码，不是readme里提到的三个空格
可以告知我一下解压密码吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lz520520/railgun"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月2日(星期四) 上午10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lz520520/railgun] 大佬请问启动密码怎么获取？没有您的联系方式，没法儿私聊 (#12)





 
好好看pdf吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lz520520** [comment]
仔细看readme.md和release说明啊
