### ISSUE TITLE
作者您好，想向您咨詢一些關於使用golang編寫java反序列化相關漏洞的編寫

### ISSUE THREAD

**Issue by adeljck** [lz520520/railgun#16]
作者好，我最近也在自己編寫類似exp合集的工具，不過反序列化相關的漏洞下的編寫不知道如何下手，例如shiro和struts2相關。如果可以的話，方便郵箱（adeljck@gmail.com）給一個微信詳談，或者在issue中回復一下，謝謝。

**Comment by lz520520** [comment]
主要就是如何生成序列化数据问题，这个说复杂可以很复杂，说简单就是修改几个固定字段的问题，这个可以参考msf呀，他有内置这个。
/usr/share/metasploit-framework/lib/msf/util/java_deserialization.rb
/usr/share/metasploit-framework/data/ysoserial_payloads.json

**Comment by adeljck** [comment]
OK，我自己去看看源码先，谢谢老哥

**Comment by adeljck** [comment]
作者您好，又有问题需要问一下你了，想知道你的这个程序使用golang的那个gui库写的啊

**Comment by lz520520** [comment]
govcl
