### ISSUE TITLE
ldap爆破没有字典文件

### ISSUE THREAD

**Issue by xiaozhaha** [lz520520/railgun#20]
字典文件夹如下
![image](https://user-images.githubusercontent.com/48639007/148156522-854c12e9-775e-40bb-a424-3dcd9c08af42.png)
爆破模块和字典文件除了ldap之外，都可以一一对应。没有svn爆破模块，却有svn的字典文件。这是什么情况？
另外跪求更新，感觉现在一样好多工具在更新啊。
辛苦大佬了。😍

**Comment by lz520520** [comment]
这个你自己创建一个也行啊，自动读取
