### ISSUE TITLE
1.4.4beta1退出报错

### ISSUE THREAD

**Issue by jhhd88** [lz520520/railgun#25]
![image](https://user-images.githubusercontent.com/15847202/168471085-3579035e-63e1-403b-9e74-43636bc0ad20.png)

win10 x64 1903

**Comment by lz520520** [comment]
你不会是被杀软杀了吧，工具不做免杀的

**Comment by jhhd88** [comment]
> 你不会是被杀软杀了吧，工具不做免杀的

我电脑里一个杀软都没有

**Comment by lz520520** [comment]
defender，自查下吧，其他人都不存在这问题

**Comment by jhhd88** [comment]
> defender，自查下吧，其他人都不存在这问题

defender也没有，换了台电脑，同样的问题。虚拟机里还是同样的问题
