### ISSUE TITLE
功能 bug 

### ISSUE THREAD

**Issue by i-liberty** [lz520520/railgun#3]
系统 ：win10x64位  版本：版本：V1.2.8.0 20200601
信息收集 > 目录扫描 >URL导入 点击没反应

**Comment by i-liberty** [comment]
//加壳程序报毒 ESET

**Comment by lz520520** [comment]
第一个问题，目录扫描那个URI导入是忘了做了，因为考虑本来就可以从文本直接复制进来，后面版本再加上，这个影响不大。
第二问题，加壳程序本身就容易被报毒，这很正常，也没做程序签名，这个加白就行。
