### ISSUE TITLE
老是报错

### ISSUE THREAD

**Issue by syhacker** [lz520520/railgun#32]
![图片](https://user-images.githubusercontent.com/32185403/173625489-7b29e6f1-35bc-4a5c-a5bb-3fb47f4d65c5.png)

一会不用他就报这个错误

**Comment by zqboh** [comment]
我也是一直这样跳出来。

**Comment by lz520520** [comment]
这个问题之前遇到过，暂时没有稳定复现的环境，如果有能复现的场景，应该马上就能解决

**Comment by andphr** [comment]
我这边在虚拟机里使用快捷键win+d最小化全部窗口或者全部还原的时候，就大概率会触发这个弹窗

**Comment by lz520520** [comment]
> 我这边在win10虚拟机里使用快捷键win+d最小化全部窗口或者全部还原的时候，就大概率会触发这个弹窗 又试了一下，是在工具最大化的时候，使用win+d会报这个错误

ok，我刚测了下，问题应该可以解决了，我晚点发新版本

**Comment by lz520520** [comment]
已更新，可使用新版本

**Comment by andphr** [comment]
![image](https://user-images.githubusercontent.com/45727255/176061823-a1d32592-41f1-4799-a989-9d0147d63455.png)
大佬，好像还是不行。操作系统是win10，打开railgun后最大化，然后最小化，就报错了

**Comment by lz520520** [comment]
> ![image](https://user-images.githubusercontent.com/45727255/176061823-a1d32592-41f1-4799-a989-9d0147d63455.png) 大佬，好像还是不行。操作系统是win10，打开railgun后最大化，然后最小化，就报错了

额这个问题确实还有，如果不最大化，暂时没有问题，UI库有问题，反馈给UI库作者了，暂时还没定位到问题。

**Comment by lz520520** [comment]
> > ![image](https://user-images.githubusercontent.com/45727255/176061823-a1d32592-41f1-4799-a989-9d0147d63455.png) 大佬，好像还是不行。操作系统是win10，打开railgun后最大化，然后最小化，就报错了
> 
> 额这个问题确实还有，如果不最大化，暂时没有问题，UI库有问题，反馈给UI库作者了，暂时还没定位到问题。

更新了，找人测试应该OK了，还有问题可以反馈
