### ISSUE TITLE
建议添加被动子域名收集功能

### ISSUE THREAD

**Issue by clasy0947** [lz520520/railgun#35]
被动子域名收集可以快速、无感的收集目标的子域名，在渗透测试中经常使用

**Comment by lz520520** [comment]
被动收集思路是啥，这也不是burp

**Comment by clasy0947** [comment]
通过调用riskiq、virustotal等平台的API来查询子域名

**Comment by lz520520** [comment]
> 

额，这个你可以选择oneforall，因为他做的已经很不错了，而且一直在维护，所以我砍过这个功能，而且这功能很吃带宽，一般就放vps跑
