### ISSUE TITLE
能否提供Mac版本

### ISSUE THREAD

**Issue by Vicl1fe** [lz520520/railgun#45]
能否提供Mac版本

**Comment by lz520520** [comment]
在优化功能和UI，优化好了会适配mac

**Comment by Vicl1fe** [comment]
Thanke you

**Comment by 0nion1** [comment]
+1 给作者点赞 同求mac版本

**Comment by lz520520** [comment]
mac版更新了，可以尝试下

**Comment by AduraK2** [comment]
章神，Mac版本的ui有点小问题，不适配系统的深色主题。如果使用的是系统的深色主题，会导致页面的字体没法看清。
最后，希望章神也能出一个linux版本的，因为平常工作中linux虚拟机用的较多。

**Comment by lz520520** [comment]
mac用户应该比我懂mac吧，我只是临时编译了这个版本，plist找找禁用主题配置，linux暂时搞不了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lz520520/railgun"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月26日(星期一) 下午2:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lz520520/railgun] 能否提供Mac版本 (Issue #45)



 章神，Mac版本的ui有点小问题，不适配系统的深色主题。如果使用的是系统的深色主题，会导致页面的字体没法看清。
 最后，希望章神也能出一个linux版本的，因为平常工作中linux虚拟机用的较多。

**Comment by 107295472** [comment]
没源码呢，我想学学怎么用控件呢

**Comment by lz520520** [comment]
> 没源码呢，我想学学怎么用控件呢

额，这工具文档里提到了，是用的govcl，他基于lazarus，你要学，你去看govcl和lazarus文档就行，lazarus是delphi的开源版，去看delphi也可以，只是移植到了go

**Comment by 0nion1** [comment]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/53221874/210583813-74bd90fe-a216-4e98-a882-4731e6dd8a8e.png">

**Comment by lz520520** [comment]
> 

这个应该需要给app里的主程序可执行权限，有的mac好像默认不给权限

**Comment by lz520520** [comment]
> mac 刚刚发布的最新版本 <img alt="image" width="260" src="https://user-images.githubusercontent.com/53221874/210583813-74bd90fe-a216-4e98-a882-4731e6dd8a8e.png">

这个应该需要给app里的主程序可执行权限，有的mac好像默认不给权限

**Comment by 0nion1** [comment]
确实可以了，感谢作者，不过感觉还是windows版本的那种ui用起来更舒服一点。

**Comment by lz520520** [comment]
> 确实可以了，感谢作者，不过感觉还是windows版本的那种ui用起来更舒服一点。

都是系统原生UI，跟OS有关，这个没法
