### ISSUE TITLE
端口扫描的时候可以加socks代理吗

### ISSUE THREAD

**Issue by fengzirock** [lz520520/railgun#47]
端口扫描的时候可以加socks代理吗

**Comment by lz520520** [comment]
这个没必要吧，你自己本地搞个socks工具让程序走就ok了呀，像proxifier




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lz520520/railgun"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月29日(星期四) 中午11:27
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lz520520/railgun] 端口扫描的时候可以加socks代理吗 (Issue #47)



 端口扫描的时候可以加socks代理吗

**Comment by fengzirock** [comment]
- 好滴我刚刚就在用这个方法了
