### ISSUE TITLE
启动密码

### ISSUE THREAD

**Issue by jinonz** [lz520520/railgun#49]
作者你好，README.MD没有找到应用启动密码。

**Comment by lz520520** [comment]
emmm，最后一行

**Comment by jinonz** [comment]
是我眼瞎😂











来自手机的邮件


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月5日(周四) 中午1:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lz520520/railgun] 启动密码 (Issue #49)




 
emmm，最后一行
