### ISSUE TITLE
可以多加点编码类型吗？

### ISSUE THREAD

**Issue by timetravel-boy** [lz520520/railgun#59]
比如base32，base16，CTF中遇到的解码

**Comment by lz520520** [comment]
可以，有参考列表吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lz520520/railgun"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月23日(星期四) 下午3:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lz520520/railgun] 可以多加点编码类型吗？ (Issue #59)



 比如base32，base16，CTF中遇到的解码

**Comment by timetravel-boy** [comment]
base32,base16,base85,base58,base36,base91,base92
