### ISSUE TITLE
怎么调出exe，看了全都是go文件

### ISSUE THREAD

**Issue by kabujiji** [lz520520/railgun#60]
本人刚学，不知道如何调出GUI，全都是go文件没有exe,是要转换还是咋地，一头雾水，看了你写的go文件，看不懂，哎，硬是看了一个小时，怎么转exe文件，不会转，看网络教程blibli黑客来的。gorailgun.exe到底怎么来的呀，大佬

**Comment by lz520520** [comment]
额，这个没有源码提供，哪来的转换，就是编译好的程序直接用

**Comment by kabujiji** [comment]
找了文件夹没有exe呀，没有可以点击运行的呀

**Comment by lz520520** [comment]
你不会用github？在release啊

**Comment by lz520520** [comment]
你别解压出来，压缩包里有吧，解压出来如果没有，有没一种可能，你杀软杀了

**Comment by kabujiji** [comment]
都说了第一次登github，你第一次就会用阿。
不过万分感谢阿，大佬
真心谢谢你
我还以为要等几个月呢。哈哈

**Comment by kabujiji** [comment]
我点的是code。第一次总是美好的，就比如说第二天你就回复了。
第一次在github和人交流，谢谢，给了我很好的体验，今天是我学习的第三天，
这三天刚学完cmd和py,还在背单词

**Comment by lz520520** [comment]
加油！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月4日(星期六) 下午3:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [lz520520/railgun] 怎么调出exe，看了全都是go文件 (Issue #60)



我点的是code。第一次总是美好的，就比如说第二天你就回复了。
 第一次在github和人交流，谢谢，给了我很好的体验，今天是我学习的第三天，
 这三天刚学完cmd和py,还在背单词

**Comment by kabujiji** [comment]
嗯嗯
