### ISSUE TITLE
linux 启动server后无法找到server.crt

### ISSUE THREAD

**Issue by liu1998-yowu** [lz520520/railgun#73]
linux 启动server后无法找到server.crt，手动生成后。重新运行server会生产一个全新的tlsauth目录。ubuntu以及kali都测试了，无法启动server服务。并没有使用--tlsrefresh 参数。
自动生成没有成功
![image](https://user-images.githubusercontent.com/81906221/233762962-5ab5f8f3-bc82-4297-9b78-dfe3436058bd.png)
![image](https://user-images.githubusercontent.com/81906221/233762990-f33765b5-5440-4c07-83cd-0fe087c30530.png)
尝试手动生成
![image](https://user-images.githubusercontent.com/81906221/233763086-dbf39ab9-de3e-42bf-bece-a87e756b880c.png)
运行服务
![image](https://user-images.githubusercontent.com/81906221/233763167-b524524e-1b33-4175-b387-bb8af13d767f.png)
发现tlsauth目录刷新了，无法正常运行server
![image](https://user-images.githubusercontent.com/81906221/233763185-6a736f0c-109e-4fe0-854d-4931a211fac9.png)
求大佬指教

**Comment by lz520520** [comment]
文档里有个脚本吧，是不是脚本执行失败了

**Comment by liu1998-yowu** [comment]
测试后发现1.5.2可以正常运行1.5.4无法运行
![image](https://user-images.githubusercontent.com/81906221/236237999-37857cbe-9e48-4da4-8e49-bcd5bd72e3b4.png)

**Comment by lz520520** [comment]
文档里有生成命令，你可以试试，可能是openssl版本太老了
