### ISSUE TITLE
exe程序打开没反应

### ISSUE THREAD

**Issue by ELIAUK000** [lz520520/railgun#74]

**Comment by ELIAUK000** [comment]
正常启动，防火墙和杀毒软件也关闭了，程序没有响应，报错信息也没有
![image](https://user-images.githubusercontent.com/126651596/233916527-511e8559-8e5f-43db-ac12-5a776e821e83.png)

**Comment by lz520520** [comment]
只可能是杀软问题了，有自带杀软的，不存在兼容问题
