### ISSUE TITLE
请问下大佬 gRPC配置问题

### ISSUE THREAD

**Issue by niuTT** [lz520520/railgun#76]
我是第一次使用，这个grpc服务端是在自己的vps上启动吗，服务启动报错，不知道是为什么

![image](https://github.com/lz520520/railgun/assets/41726904/6f1d37b7-7253-4def-b5e8-aea0901c8e0e)

**Comment by lz520520** [comment]
你写错了，文档写的很清楚，文件名

**Comment by lz520520** [comment]
两遍文件名
