### ISSUE TITLE
Mac版本左侧字体较大

### ISSUE THREAD

**Issue by LztCode** [lz520520/railgun#88]
1、rt，mac版本左侧字体与右侧面板字体大小反差太大了，希望可以调小一点，或者加个字体大小设置，mac分辨率太低了
<img width="351" alt="image" src="https://github.com/lz520520/railgun/assets/73683679/057fccb3-cf8f-497e-a01f-57685b62ee5f">

**Comment by LztCode** [comment]
最近看到两个项目是wails开发，感觉这个UI框架不错

**Comment by lz520520** [comment]
已经用过wails开发其他工具了，后面会将railgun逐步迁移到wails
