### ISSUE TITLE
暴力破解时程序闪退

### ISSUE THREAD

**Issue by ab-Alex** [lz520520/railgun#95]
使用环境mac arm64

爆破ftp时闪退
<img width="1318" alt="image" src="https://github.com/lz520520/railgun/assets/43507436/f805bf62-9534-47bf-b4ce-5be02a31e339">
错误信息：
[1.txt](https://github.com/lz520520/railgun/files/14532850/1.txt)

**Comment by lz520520** [comment]
最近忙完会发一个重构的版本，有一个全新的UI，暴力破解和编码转换者两个会先做上。这个看起来是UI库有问题
