### ISSUE TITLE
465 端口 STMP SSL 爆破误报

### ISSUE THREAD

**Issue by en0th** [lz520520/railgun#99]
显示爆破成功，但实际上没有账户和密码。
PS：希望作者能够增加复制功能。
![image](https://github.com/user-attachments/assets/b5160d85-4ba3-4cf9-9ad8-f8c775ae7a0a)

**Comment by lz520520** [comment]
有没有可能你这个目标支持匿名登录。
复制？你选择不就能复制吗

**Comment by en0th** [comment]
我试过通过openssl尝试发送指令，但是都会提示需要验证。553 authentication is required
没有提示复制功能，但是可以通过快捷键 Ctrl+C 复制。

**Comment by lz520520** [comment]
输入密码如果认证错误那就没问题，空密码其实也没不影响啥，我也没你环境，我这测试都是正常的

**Comment by en0th** [comment]
我试过空密码会提示，535 Error: authentication failed。这个检测的是coremail提供的服务。

**Comment by lz520520** [comment]
我意思是你输入密码也会提示成功吗，如果也提示那就确实有问题，没提示就没啥影响

**Comment by en0th** [comment]
如果输入账户不会提示成功。
![image](https://github.com/user-attachments/assets/50d3aa62-c0fc-4dd9-b52d-6e562fce05fc)

**Comment by lz520520** [comment]
那这个影响不大，账号密码全空的情况有误报，这个确实没测过全置空的场景，其他应该都正常，后面我找找环境复现下

**Comment by en0th** [comment]
嗯，我检测了，发现没有影响。邮件服务正常安全运行，该上的限制也都上了。
